name: publish
on:
  push:
    tags: ['v*']
jobs:
  publish:
    permissions:
      contents: read
      packages: write
    uses: ippoan/ci-workflows/.github/workflows/lib-publish.yml@main
    with:
      node_version: '20'
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
